// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextureMarket.Data;

#nullable disable

namespace TextureMarket.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231026113116_seededTexture")]
    partial class seededTexture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TextureMarket.Models.Texture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Textures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "texture1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "texture2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "texture3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "texture4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "texture5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
